#!/bin/bash
# Copyright (c) 2022 Elektrobit Automotive GmbH
#
# This file is part of nautilos-repo-setup.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
set -e

ARGUMENT_LIST=(
    "user:"
    "password:"
    "no-init"
    "local:"
    "production:"
    "test"
)

# read arguments
if ! opts=$(getopt \
    --longoptions "$(printf "%s," "${ARGUMENT_LIST[@]}")" \
    --name "$(basename "$0")" \
    --options "" \
    -- "$@"
); then
    echo "ebcl-repo-setup"
    echo "  --local <distpath>"
    echo "      Use local distribution that must exist below <distpath>"
    echo "  --test"
    echo "      Use EB development snapshot artifactory server"
    echo "  --production <release_date>"
    echo "      Use EB production artifactory server for"
    echo "      given release date in format: YYYY-MM-DD"
    echo "  --user <user>"
    echo "      Artifactory user name"
    echo "  --password <pass>"
    echo "      Artifactory password"
    echo "  --no-init"
    echo "      Setup environment but do not create"
    echo "      apt repos and cache"
    exit 1
fi

eval set --"${opts}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --local)
            argLocal=$2
            shift 2
            ;;

        --production)
            argProduction=$2
            shift 2
            ;;

        --test)
            argTest=1
            shift
            ;;

        --user)
            argUser=$2
            shift 2
            ;;

        --password)
            argPass=$2
            shift 2
            ;;

        --no-init)
            argNoInit=1
            shift
            ;;

        *)
            break
            ;;
    esac
done

# variable setup according to parameters
if [ -n "${argProduction}" ];then
    dist_mode="production"
    ebcl_profile="${HOME}/.ebcl.production"
elif [ -n "${argLocal}" ];then
    dist_mode="local"
    ebcl_profile="${HOME}/.ebcl.local"
elif [ -n "${argTest}" ];then
    dist_mode="test"
    ebcl_profile="${HOME}/.ebcl.test"
else
    echo "No setup mode specified, use --local, --test or --production"
    exit 1
fi

echo "Running in [$dist_mode] mode..."

# sanity checks
if [ ! ${dist_mode} = "local" ];then
    if [ -z "${argUser}" ] || [ -z "${argPass}" ];then
        echo "${dist_mode} mode requires --user and --password"
        exit 1
    fi
fi

if [ ! -e "${ebcl_profile}" ];then
    echo "${ebcl_profile} environment file not found"
    exit 1
fi

# copy selected env template to target
cp "${ebcl_profile}" ~/.ebcl

# update template with parameter settings
if [ ! ${dist_mode} = "local" ];then
    if [ -n "${argUser}" ] && [ -n "${argPass}" ];then
        echo "Updating credentials in ~/.ebcl"
        sed -i -es"@__USER__@${argUser}@" ~/.ebcl
        sed -i -es"@__PASS__@${argPass}@" ~/.ebcl
    fi
    if [ -n "${argProduction}" ];then
        echo "Updating release in ~/.ebcl"
        sed -i -es"@__RELEASE__@${argProduction}@" ~/.ebcl
    fi
else
    echo "Updating dist path in ~/.ebcl"
    sed -i -es"@__DISTPATH__@${argLocal}@" ~/.ebcl
fi

# create repo files and update cache
if [ -z "${argNoInit}" ];then
    # shellcheck source=/dev/null
    source "${HOME}/.ebcl"

    echo "Setup EBCL repositories..."
    clean_repo

    init_auth

    # NautilOS release repositories
    add_repo release/containers
    add_repo release/xUbuntu_22.04_debbuild

    apt-get update
fi
