#!/bin/bash
# Copyright (c) 2022 Elektrobit Automotive GmbH
#
# This file is part of nautilos-repo-setup.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
set -e

A_MACHINE=https://artifactory.elektrobit.com
A_DIST=eb_corbos_linux_nautilos2.0-releases-generic

ARGUMENT_LIST=(
    "user:"
    "password:"
)

# read arguments
if ! opts=$(getopt \
    --longoptions "$(printf "%s," "${ARGUMENT_LIST[@]}")" \
    --name "$(basename "$0")" \
    --options "" \
    -- "$@"
); then
    echo "ebcl-releases"
    echo "  --user <user>"
    echo "      Artifactory user name"
    echo "  --password <pass>"
    echo "      Artifactory password"
    exit 1
fi

eval set --"${opts}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --user)
            argUser=$2
            shift 2
            ;;

        --password)
            argPass=$2
            shift 2
            ;;

        *)
            break
            ;;
    esac
done

# sanity checks
if [ -z "${argUser}" ] || [ -z "${argPass}" ];then
    echo "requires --user and --password"
    exit 1
fi

# print available release dates
for href in $(
    curl -u "${argUser}:${argPass}" -s $A_MACHINE/$A_DIST/ | \
    xmllint --xpath "/html/body/pre/a/@href" -
);do
    release_date=$(echo "${href}" | awk -F\" '{ print $2 }')
    if [[ ${release_date} =~ /$ ]];then
        basename "$release_date"
    fi
done
