#!/bin/bash
# Artifactory sync to local system

set -e

ARGUMENT_LIST=(
    "user:"
    "password:"
)

LOCAL="/var/tmp/nautilos"
REMOTE="https://artifactory.elektrobit.com"
RELEASE="${REMOTE}/eb_corbos_linux_nautilos2.0-debian-remote/release/"

# read arguments
if ! opts=$(getopt \
    --longoptions "$(printf "%s," "${ARGUMENT_LIST[@]}")" \
    --name "$(basename "$0")" \
    --options "" \
    -- "$@"
); then
    echo "ebcl-sync"
    echo "  --user"
    echo "      Artifactory User Name"
    echo "  --password"
    echo "      User password"
    exit 1
fi

eval set --"${opts}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --user)
            argUser=$2
            shift 2
            ;;

        --password)
            argPass=$2
            shift 2
            ;;

        *)
            break
            ;;
    esac
done

if [ -z "${argUser}" ];then
    echo "No user name specified, try --user"
    exit 1
fi

credentials="--ask-password"
if [ -n "${argPass}" ];then
    credentials="--password ${argPass}"
fi

mkdir -p "${LOCAL}"
pushd "${LOCAL}"

# shellcheck disable=SC2086
wget --user "${argUser}" ${credentials} \
    --mirror --recursive --no-parent --convert-links "${RELEASE}"

find . -name index.html -0 | xargs rm -f

popd
