#!/bin/bash
# Copyright (c) 2022 Elektrobit Automotive GmbH
#
# This file is part of nautilos-repo-setup.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
set -e

A_MACHINE=https://artifactory.elektrobit.com
A_DIST=eb_corbos_linux_nautilos2.0-releases-generic

ARGUMENT_LIST=(
    "ask-password"
    "credentials:"
)

# read arguments
if ! opts=$(getopt \
    --longoptions "$(printf "%s," "${ARGUMENT_LIST[@]}")" \
    --name "$(basename "$0")" \
    --options "" \
    -- "$@"
); then
    echo "ebcl-releases"
    echo "  --ask-password"
    echo "      Ask for credentials"
    echo "  --credentials <filename>"
    echo "      Credentials file, will be deleted after call"
    exit 1
fi

eval set --"${opts}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --ask-password)
            argAskPass=1
            shift
            ;;

        --credentials)
            argCred=$2
            shift 2
            ;;

        *)
            break
            ;;
    esac
done

if [ "${argAskPass}" ] || [ -z "${argCred}" ];then
    read -r -s -p "Enter Artifactory Username: " inUser
    echo
    read -r -s -p "Enter Artifactory Password: " inPass
    echo
    echo -e "user=${inUser}\npassword=${inPass}" > ~/.wgetrc
else
    mv "${argCred}" ~/.wgetrc
fi
trap "rm -f ~/.wgetrc" EXIT

wget_out=$(mktemp)
# shellcheck disable=SC2064
trap "rm -f ${wget_out} ~/.wgetrc" EXIT

# shellcheck disable=SC2086
wget $A_MACHINE/$A_DIST/ -O "${wget_out}" &>/dev/null

# print available release dates
for href in $(
    xmllint --xpath "/html/body/pre/a/@href" "${wget_out}" 2>/dev/null
);do
    release_date=$(echo "${href}" | awk -F\" '{ print $2 }')
    if [[ ${release_date} =~ /$ ]];then
        basename "$release_date"
    fi
done
